---
apiVersion: v1
kind: Namespace
metadata:
  name: event-processing
  labels:
    app.kubernetes.io/name: event-processing
    app.kubernetes.io/part-of: event-automation
    app.kubernetes.io/component: stream-processing
