---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-endpoint-mgmt
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    # ROSA: update to your fork's repo URL
    repoURL: https://github.com/krab7191/EA_gitops_OCP
    targetRevision: main
    path: instances/event-endpoint-mgmt
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: event-endpoint-mgmt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true