---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: production-flink
  namespace: flink
spec:
  serviceAccount: flink
  mode: native
  flinkConfiguration:
    license.use: EventAutomationProduction
    license.license: L-CYBH-K48BZQ
    license.accept: 'true'
    taskmanager.numberOfTaskSlots: '10'
    state.backend.type: rocksdb
    execution.checkpointing.interval: '5000'
    execution.checkpointing.num-retained: '3'
    execution.checkpointing.incremental: 'true'
    restart-strategy.type: failure-rate
    restart-strategy.failure-rate.max-failures-per-interval: '10'
    restart-strategy.failure-rate.failure-rate-interval: '10 min'
    restart-strategy.failure-rate.delay: '30 s'
    table.exec.source.idle-timeout: '30 s'
    env.java.opts.taskmanager: -Djavax.net.ssl.trustStore=/certs/truststore.jks
    env.java.opts.jobmanager: -Djavax.net.ssl.trustStore=/certs/truststore.jks
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
    spec:
      containers:
        - name: flink-main-container
          env:
            - name: TRUSTSTORE_PASS
              valueFrom:
                secretKeyRef:
                  name: ssl-truststore-password
                  key: password
            - name: JAVA_TOOL_OPTIONS
              value: "-Djavax.net.ssl.trustStorePassword=$(TRUSTSTORE_PASS)"
          volumeMounts:
            - name: flink-logs
              mountPath: /opt/flink/log
            - name: truststore
              mountPath: /certs
              readOnly: true
      volumes:
        - name: flink-logs
          emptyDir: {}
        - name: truststore
          secret:
            secretName: ssl-truststore
            items:
              - key: truststore.jks
                path: truststore.jks
  jobManager:
    replicas: 1
    resource:
      memory: 2048m
      cpu: 0.5
  taskManager:
    resource:
      memory: 4096m
      cpu: 2
