---
apiVersion: v1
kind: Namespace
metadata:
  name: event-streams
  labels:
    app.kubernetes.io/name: event-streams
    app.kubernetes.io/part-of: event-automation
    app.kubernetes.io/component: kafka
