# oc get kafkauser -n event-streams
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  name: es-prod-ep-user
  namespace: event-streams
  labels:
    eventstreams.ibm.com/cluster: es-prod
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations: ['All']
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations: ['All']
      - resource:
          type: cluster
        operations: ['All']
      - resource:
          type: transactionalId
          name: '*'
          patternType: literal
        operations: ['All']
