---
apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: es-prod
  namespace: event-streams
  labels:
    backup.eventstreams.ibm.com/component: eventstreams
spec:
  version: latest
  license:
    accept: true
    use: EventAutomationProduction
    license: L-CYBH-K48BZQ

  # Administrator API access
  adminApi: {}

  # REST Producer API
  restProducer: {}

  # Admin UI with SCRAM-SHA-512 authentication
  adminUI:
    authentication:
      - type: scram-sha-512

  # Apache Kafka configuration
  strimziOverrides:
    kafka:
      authorization:
        type: simple
      config:
        log.cleaner.threads: 6
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 3
        offsets.topic.replication.factor: 3
        default.replication.factor: 3
        min.insync.replicas: 2
      listeners:
        - name: extscram
          port: 9094
          type: route
          tls: true
          authentication:
            type: scram-sha-512
        - name: intscram
          port: 9093
          type: internal
          tls: true
          authentication:
            type: scram-sha-512
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: metrics-config

    # KRaft node pools
    nodePools:
      - name: controller
        replicas: 3
        roles:
          - controller
        storage:
          type: persistent-claim
          size: 10Gi
          # ROSA: change to gp3-csi
          class: ocs-external-storagecluster-ceph-rbd
          deleteClaim: false
        resources:
          requests:
            memory: 2Gi
            cpu: 1000m
          limits:
            memory: 2Gi
            cpu: 1000m
      - name: broker
        replicas: 3
        roles:
          - broker
        storage:
          type: persistent-claim
          size: 100Gi
          # ROSA: change to gp3-csi
          class: ocs-external-storagecluster-ceph-rbd
          deleteClaim: false
        resources:
          requests:
            memory: 4Gi
            cpu: 2000m
          limits:
            memory: 4Gi
            cpu: 2000m

  # # Kafka Connect
  # kafkaConnect:
  #   replicas: 2
  #   build:
  #     output:
  #       type: docker
  #       image: image-registry.openshift-image-registry.svc:5000/event-streams/kafka-connect:latest
  #     plugins: []
  #   config:
  #     group.id: connect-cluster
  #     offset.storage.topic: connect-cluster-offsets
  #     config.storage.topic: connect-cluster-configs
  #     status.storage.topic: connect-cluster-status
  #     config.storage.replication.factor: 3
  #     offset.storage.replication.factor: 3
  #     status.storage.replication.factor: 3
  #   resources:
  #     requests:
  #       memory: 2Gi
  #       cpu: 1000m
  #     limits:
  #       memory: 2Gi
  #       cpu: 1000m

  # Deprected in 11.1+
  # Collector for metrics
  # collector:
  #   resources:
  #     requests:
  #       memory: 512Mi
  #       cpu: 100m
  #     limits:
  #       memory: 512Mi
  #       cpu: 500m

  # NOTE: adds latency; enabled for Producers tab in UI
  kafkaProxy: {}
---
# Metrics ConfigMap for Kafka
apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-config
  namespace: event-streams
data:
  kafka-metrics-config.yaml: |
    lowercaseOutputName: true
    rules:
    - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
      name: kafka_server_$1_$2
      type: GAUGE
      labels:
        clientId: "$3"
        topic: "$4"
        partition: "$5"
    - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+), brokerPort=(.+)><>Value
      name: kafka_server_$1_$2
      type: GAUGE
      labels:
        clientId: "$3"
        broker: "$4:$5"
