---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ibm-entitlement-key
  namespace: event-endpoint-mgmt
spec:
  encryptedData:
    .dockerconfigjson: AgBL96DzEugH35+AbAPs1QBNhu1DgiPgi6MCxRzDUHdCjOhJ/4o8ef7rwvHqF1pyhMkc2welKYhNlMMvAb+EsE4xOi+M3x7MZj4evyod91n1nPO6/R+nDIpmS4g3+e+1SiMH/ZKX4/oek2UfmlBKg+8GyZZZpLC5h0cOBHnMp7Vpq+9b0kmTt6xlb95bMuClL8IatO+C3Zt2luyJ0QfNLMMzk1wgsZFX/O1zK++c9o+vdxviRCj8oMMs6hb+XAEl0SmjMUUpB1Rh8ORDh7mai5TjbWk7IIjmWw5s+dcwYUR5wonvVEHMio6EnB3CZMu8VrlLCm7lpXvasl1CfFJXQcewN8tRWTWKLOPXHiQYfVrRfDu7UNZEn0TI7fQxW+ZQZLVkAcNzWNjwOnx3hfyVMDFsXi9Ppvy930LtTFV6S85/xd+IgRE/Edg3ETjI/srHLTgHI8f6kk/Aey0eSH2VcuktoijL7p26aXuxUbelZXZQdG79tFJ4/fbDWQY4TFsnMy8KfXapeQCjKMLH+osogaZStOh//uN3fpom9PNjO6SFrDiHVlj747MfydksTixRVwd2zDGx7c8hV0q4b5j5He64wkuhvZJU7QniOGFZZrlnJSibbhXMLNi25QVvAWjZwo/yqQeP9i/DuwlKCCrBwNDIyEZzh3xm362yeTWo6XCNIrfJ5t7MAB0bFESpWdtLx4qoleL2eUgC5s0YI/DPBVtyNDwZxV6IT0doH4FAhCdvIWQARJ4p9gov4LGjVMaexLKWy6Ts7ivWfNBqwbD6yYSGLMtO54oPpu3+i/BzF9JXNX1xM3ITOKIHFSVg2ZzjOheVEVWmxIljIUHYGwJjBS9IZ79tYUTHjJuZWhoo10sUmawseVDYdX75L2nj09bt3rZ+L6wzZB9wdhI7Zop0K5IPaktC9c2BviTo1IbrUkizsYeikyAI0pLD/uWMGszZdsIsfLcrMLTNhi0c9281KDwfCw0vMrDxVesjV8Pmg9SREucdzaKQc1wkYkyKOxPmGEGOon5VmESLxYX2FOjXfImStFXfztSDNO19kJG6jwtC64IbCYyrj2u8/Ri5JH9Z4eSg+yX24Oj1MBOVWmh/FgUw3TG+4we15Fbd4bxHLDl5Wpte+DSynzxMdWu/8DeQmT8DXYkegROFpzaXEPNsL1nuUmPoctTEigD7Qc4XOInunOMvijIblcY5J9SfBelTZ7UOfZXjM9kpbZxwGCihqcIGX3olJ0GAu0S0P8GAqPALxMZeKRohhvbzfmpqrvkBHCytDN/P7+wHmwEf6swqTR0v0GDoWZryQ/rDfp+PjYK6UxrDoQZDl0EugSirG5bNM+yRL/YtD3oue8B6X+/FEiAggBY3Ea0Q+6vpNiM8Wgfd86/hFfX0
  template:
    metadata:
      name: ibm-entitlement-key
      namespace: event-endpoint-mgmt
    type: kubernetes.io/dockerconfigjson
