---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ibm-entitlement-key
  namespace: event-processing
spec:
  encryptedData:
    .dockerconfigjson: AgCu74LraNJjJOpzT2CjY3WqsV2qj2/a7RoqMaswDb9GsyyxGSNczo6OoXoC7waiuLS5amQPh3uoeJuz0Lj5ZOKzwhwYQR+vWiGV7GXJ+IgoyTqw42jCZ9598X2iocvtOjICxl3UvaN/0ykb6Vl+w9FHENszIkveVOxaEf1rIe2ZHhamFIvVwHvkWedG90Hfaxf8vRuVtUmmad7co9hZUu09zi43mVd86SsjkspNEZfexeJmHhbRWPzBEGcRw7AGzwwoAFDm4xszpugOD/+rl7LyYPYVR6PTVpad4H8rig9hUUyjfzf2Eaz/bbQEcriNM95PbgKsZVnUaHXxN62E02WwzWrBblAv6S5Ht2iTt0LrePUyNwJmie91QdBBEPK9/WA2+BLsBBYAvAWQyM90Itzg1XsxeMJ6NZSbsAcT3Rrvb7Mb9q9eZmI9x2JmtfQkTp+uLKciyFpAycWdN6vQLuO5XsZOGjyDBhM0tGmLphlh2Ie1Y32wucVrmHsfri8efx8FNQ9Jj3Y6UNLNGxmZx2jnzS2h2qFcgCx5MIcJNIWy4apGl763SGrf+ij1/iYVSnAaKLcSt+M8ziIno9femKII55LDwhb64pfzWr+8eu7QPF9hq/TWHq6X5Dfek9djtzi6iJT6EbL3fY0COtGbqmaAfBLYzrGOE8pLYD4zKOHBX6SRa9q4CUW76ZCfL7yiz2dt8nlnZ8m07RcjJeRh7ZP6qea2mvWZhXAHuQKS48svWZo8pPw3hMmUL1SpRhhZfDzI4fYd9dujoZBts6s0OlhhE9F5JjZwydJMl4oMItrXLscrPwIxDW+LTNGxs40430yCPfVF7Ew5YGexXu3KRZnZAAzz+1Cw15VblPnX6nXOmoHyi3D4XHNcHPoI90rRHUv7oXfVg+4eZhzUyk/s+MbUgqkNRQoqYYg4AYuvrNGRYPAa0/wgBr9Ujp3oUVn1j7Ze2P/wwMZKaW4ieOuL9vG+KtdUwyFNqWn2GqG/UcILhFTSRT9CZqxjd7MfUy7/+oV5IxRMAsGX6IYfNvWyxyyg67vqC7XhVVAybfItIXPkzPFZF97ncR4ciNWaniLmU8gTNH3KA1Yl34x0moIi3zk8mb3M1cYdtGd4eZhbfZmSOlmXvz3eVav/8PQOkCYvvTv1KJyrgbLP0wKAJ9Lzl72QPyaCfuC016rAPEeXMeyl9q186n7dalfRi2qp+Eva9T6Gh6fIshOsSAGPPxsxtSFLGuL6OYQrlWLj4/hb3uwZQqnKkoy1UV/tq9s5HyubOlnO79FMcB/j7nkZsKQkLHstXPHYV4Ygqmi+wRVwvTLNoHHC5wXTKWS9YmSgy0QMp/bEXJy7acknXCOzsdoKb+4nbBTmHqifras2Dgh3iSAyAhM63F1e
  template:
    metadata:
      name: ibm-entitlement-key
      namespace: event-processing
    type: kubernetes.io/dockerconfigjson
