---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ibm-entitlement-key
  namespace: event-streams
spec:
  encryptedData:
    .dockerconfigjson: AgCP6fkmSktqcBuhk3wYCvmv61kHcm7DxuTw2JpcWtbG2p3XYfMqKRaPaDL9LkHYcETdr3FU7W+HL+zl/+PScYhF5pbibx2MQbGEDIt9Kxqt9SdlVQJh0EDlE5Qk6V9dt5LiMQ5bf5BVpkVxsMOSwY01vH5f9ADDNYDP+mPBteN07YXgN6LYSd5un3GHiMIpOVl7VJYi2FPb9Ym9j/LETnON3XVSEiKPZXcCPFYQ3USkYFo0S2LpNja1Vq09YtmOucLrzU1w/EyZvr2DQ07zh+JpjU4b3eZeuep3yaI+GE38qg3Jv2tekV85Pn4ZAOi+flU+HFKWB/bvVF0Q+yV44EMZhwkj7+BiYho5+AOFFhX+5ats6pyOVk/9//HRZdOnszTQsZTHoJuPqyz+aq/HTWEzEI9I7x9+1DIy3uWQjfdmVNGcVFrZHSv+zDaJTv71qEwz3nZw3XZpIoBCo1CGBJfYu3Sm5Y34enHQdlopb2vkSEF2kwFHc03Dr15cueZyKkiva1K/O0xUcsE7E+w0nyWSGB2guhPr9uZ+iwfjZ9VfUP2ReAtjXxBUK1B407g0es0k2v+KJrQ9bH+IdJALP1gAcR1yWqLP8kmoKWBK9oZX7wEnu9ZVy7k9wLHlCbAtjuuYVFEu9i2FFF4g0pH49Q4e/wDJ9Nr9HdGJ4b5bVuuDtxUJheD9r5mwz+Umo0hCPMn0V0e+uXmUV1TOm/romJTtDvCRR3FXHvQqvLJo63JETOkyKzXWkbBrUaNOUGr3UxDyc1NhqJtsAWxJkvmN7vS6ZXeRaPmdtVAtQnUw+ydKU26napRuHbBHKwQc5Hgvtz7X+quZ8FzMIVAtHAFt7dc3H+P73Nvgd2THmJXhqj/Ba/B0p47jvuLTpc0733DV9ySdJN81feSjE3wta5BHdclmpoxVXcEwp2xDmZJamTR7AiqU7HPb5ZVrW830qRfx2B+DMj5Zm/iFfN6eKuzVs5viIp5iFy8ETyIpAinmOyWOuPbkr5Zj7RHwYmK6NiOdAu9nxjJHRIpZTgSrDcqpZ7vKyBoeN9MUlKVEUHffAWAjC1zh1aDS22p5TcMSIZfIhOq9ScS1XKb5BlJuSWgONKEWyj7trwcraNNdiVrfz2Y1JrsCmtcTsViv7DfQCOa7EYBq/gtlWZibZCKbWE/e0xqi/jyx8YI3B0ABf2bnJARu3x9XugBvs7GQcU34qEbEXpP2Ec91t7DfxkngoJm5QU5YtDPNeUpqwpwzNXIcyYrFm9rkWlnBYx+BdAP3dTLtB77sEHStFvWe2TDCHziHQ/q01Nz6KONfIcLMJLRV4m6ptbr+DwiRQHjlZLcv7nuCTEOmJ0v3R0tfUzImGe/GEMQADhg8Jsp/BVY5M/7rDS0nLUDn/x93
  template:
    metadata:
      name: ibm-entitlement-key
      namespace: event-streams
    type: kubernetes.io/dockerconfigjson
