---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ibm-entitlement-key
  namespace: flink
spec:
  encryptedData:
    .dockerconfigjson: AgA+WoO3O0QznCkpGE0r7A5IgL7GBamcSPKn3A5bnlX83V2l9raScvNX08aN326hV/wh2e73DWTOXCVAeVpzrSsDjhaqGljrb74kOZEPrXkBjdcA9ih33MC/1hl8RRuf4pmqG4AqJjdZymgGa0Uo6E6rLyMV6bXiuUPD0Ai4Y0JTqUIB+Ehgbowr/H6ooNljBqObiFcxNMbKHvHtvk9V0Pcqa+Cmx196sk/QiJR0cVahk8zA2q5EoNTU/eCiL+FSMqKkallOi9+lo+BQuWYoA7/UxY+v8lDkGJj2eF0zrsqY36Hv5TgyDL12nuQ/qKS0BoMHE0U3B7lF4FIuDBB+fOBXYiZpHAZMWquzkPqvzXPWjK5rb9ooBv7sKFDmIlGgeXjRjVq+B7wNii1pKwx3y0XlbmXERIjazrH4WVIaQUXq9ZfVj3X+5+4XfHGuY1O1zO2bI423EcpKNLPnazaO+L8dg+kt9q3LEaRmr1pW13TEQzovCqhjDf76rv5n+V30sRxtBnKpOGB3Q84tOamsP7oz6pkZav7yi/gzqiSNORe/KJkiD5wSjaF/R70BevNKZX1yJsEJnCEKj9BOCjPUHwFCMqIREKutgNcqCYKb3WrJ/goOCLDy+YA3yPBB8eWOXdbYWYZt3AWz71kL7siVlIIRUmS1hx2HMSd4ulLrsZR8Wl7Uh7vOK6cy/ALNvwnRaKelWj60HexP0rjJLHXuTygaYRMUKAuP5+H/Cbw0XRTxRQDnB1idb5FT778DT0fC16sdz9w1AKcOXAaQ1zxIhTlvYK60S/awvaUTJX1OA2LB1rBpPd/3wR4i0OasM98PvLooHF6hsbcAgNjhET8aeLL6RU8tmf7hI/SaIDZHRgbZf9Te5ZIlNPs3DgYkdaEVLT5AHrJn4XR/YfkVrrX61lBPHLjvRR4p2obd7K91OHNw8vn9gHM04lIX9UD3Kdl5HciPv0JoGN4QWkCxEmjHzzeSNm9dM0bB1Hb5+yQlGYnfQEVH7Iin3SFS8Ir/MDKqNY+CYrtU8cUXDG15phIxQXldmM0BSeo7PW/8keaTQQH50JyAn731X/VtFce6o12jSGfiniceD3YexDnayen9UuqPICW5ZoRdPYexyl2s4HEjEmt0YijDqglRS6oP0Iui+4+cvETogMPRGHXzV/Zbvu7tW/diNs0dFDgM/uQXSQxDJJcucK6rwAu0pcW6GBk/o9/D9Ul2fC96xEcm8hK145yOHoEviUegtZBY4igc/eghYLqiRkWCWeX1njmWwhXG5u4GLrxAbtSIC5KMCLlLO70i/yjQXmGePhUFkkr1JWuHjGJlqmZPd430NH9o+64fX6JwoqM34TQ4fPMvtb1ufWeBup/EZ6/fzmrtzyvaOzAoZ2DE6Ysr
  template:
    metadata:
      name: ibm-entitlement-key
      namespace: flink
    type: kubernetes.io/dockerconfigjson
