---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ibm-entitlement-key
  namespace: openshift-operators
spec:
  encryptedData:
    .dockerconfigjson: AgCjoMiEA8WbefCOjM9f1RQeNs4VGz8YWqmvGhqmH3ZkGbtEur+RZxxll9YMIUoI34jTcQKuS9iTlDP3SDG6T1PaHVxKC9HmENUmbPGKVe2IVMQwTbLvBrho8+O82EXQkUsHdlRQyL7tQkzCPhJKpCMO5s2p82jbHC/xdsnLO8ErOY4KehXfy+i4ERxR4RdITt13OEoBW+vR+HoHfW6jTsAnpChdlILIqoW8nFChct7DwvfQsuWx1cmQlLPMespxbVmEXC2HnWQlhwVTIL25EvRoPNE9+D6m5wYMkXRnNST4O6WL3uVYOBLK1FBQHCl/1VGrOwNpJYIv/X1HseXAn6o3MKSeQ390zRgr8UnW9XcHr3rNbF8dkCFtzMWuVuwarsjqVTKbiboL6hayTYeMtKGIlm0z0eyTXcAfHm27ADQQTvVTrz0va862ESlSYkZ+nnfGQYapMYUJ4LO4dYGlvWZidQZQI6GveW6RaEutHznqE6QdiIB6LgJlgcXOdtsEmJcAoBu6eWW7s2xoFK1T/rnkq8sfuA9tYxuw+ZOU4MUTcDtqrY7BYtCbHPBhGEYf9OFZ+5krjaTRJkkLDkZRd+x8JQZLUx7LGzH8aJ2uiizEcLZpLWiEReM+Bgj/VUsOQo6tXc9C7u18dX9UPxgch3J28kEoPtJGJTCVfFyjQO9vJ+gNzQKDa6djhmShKa7ycCSdawXhNQZhfEXwJs64Al6Ccyc4uQYFmSg4P2IosRCyM9B1AuFDwqfDMs/8jLebynWGvDfYf+24KktQsS9f7JWLAASlQ96GxhvxqGtQK8L/QH0R7lh+FXC3hKd7RwkGIJ/3mE/pOSSRyqpwVbWibZn3lwCz6TyPFoBKgJ8i60xvqUaGJGnuCGgsfev9Xb0/OoyT28Wdt4NA+BX9uvF/Ez4ZDYWeS1FQyKKfe8/kIZqvhqaj4Vi7V9XD36rQE4dMph7u333LwiCb+/BJ4l/O3KDW8xTOI1LAP4PGvb/vu0B2cQb70izt7wGlWHUBnwCriY//M+jk+GXKhSNYUykoRuovQfWX4V+dVh1ONbTrpKr3S79gdiyrZ7Ds3CGSjXVRS9qW5rrIMevMywILBOhpr1LBb/f54Tsz7nbUWE+FBk2y0sQ671AbFwG9JVrM/uSrGXyvMD2x6jCzcBYM9eOWAPaXvfAIrwAYUBLNdRw1VjbnUXbE2OXHX6x77kpe5gQUHoUxl/8qOLn7obA9OuoFrYus+puPqAUL+pBYynawwCqcr2M60pst0OqJmn43rb2FmMsCgR2C6+3iMhnWFnXQ/3gm3THqTEFH+BDgPKsfsSDcBAFF+rVbgL2mLhiHYXuIGpOmiGqF1tTXnKzIL+Js69c8A5hBy4Cxdng/qjstRlJ/cZFB2Thk
  template:
    metadata:
      name: ibm-entitlement-key
      namespace: openshift-operators
    type: kubernetes.io/dockerconfigjson
