---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ssl-truststore-password
  namespace: flink
spec:
  encryptedData:
    password: AgChvzG0iLpHCNA1qt3Nd4cpsdl0V4ojUsLDvyAb2Fp8LDxctavFFi9o4Gua4hpd2DxAzOq549xAjCYEaMXTb2KbS2EPqk72gLi3NZTnM2hPIVPwOHC5BltI46X4lNe6wD/hbDyr/IMakchi9s2Y4cSgvdNolAwfSO5FrKDRar6XrbnGj1lPMDURchNoC4xCCE5HTSHJI0XUuI0Q1sqORtv0AdsHfKfjVR4yfVjHPRnddHq9frpeBJJXMLegLt4HdUJ1R9UCRbfrx0cpSPPYxLTRgPxwLCWwvkr668bZ6cWMDKl8XvPIiuAQrGn0eISUzUdnIN+xEBvnR7m3Gi/ilRJrTU6sNE62/99ddBENo4Vy8hbxITb/gqECcblrJTuOFiiFUXm9j05UhlbsgFPxhPywYHE1pAgrKyiPT29lmJbxY3ihDUWUeJiATCIH4fAW05ZwdiD8Jbm/gb09S4MDWfttMfZ3baGh9ipggm5wv3Gp6SrxDaP+emhMi2FJGsdQ2jKq/teXhg5n8B3F3gkXOOmyaYlGRjZWM2McTGvdBeIsGnaVKVEwcaxM0uBQ1vKAAsrTpHBXVKrdxYmQ59ijPpG2Bp3osp3LV8KgJJJNz+YABAyUTPlcc61kOvgaS8kLJhMLidrkNNLPmHHx7bv5Dyt2XxAnRy9tLHzf74BaSf2n7wSPygbOL2QgHlcywMmxVocWi3JOGtDhZ9GhSQ6bH1jc+Rbv/RmhcRwOeKr2UTXsfw==
  template:
    metadata:
      name: ssl-truststore-password
      namespace: flink
