---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ssl-truststore-password
  namespace: event-streams
spec:
  encryptedData:
    password: AgBofV+ATiH7FEjGw8Okify8tiGJFhLg8lW5KRLwB+29WuImY1fv/68nAUURCuGThYp2M0eXL4X0WQgh8F2WOM9N/V1oWkyAdfYhqS+CTZAHgB8sKed3PZfT1AoC3jT0wJxZgQGf/YO3o1MCgPPmtN/VqhvGG4GznBW72lmXlybbdok/+wgTIiIoFomnJRtgPkWGpAz+urml0itKoHd0KWfd4/5jel/x22RpoWTjWylSxaGjdvJYJxNqs1I4SZlgUpkkH9iRAgI45kmcIAv6HgeQLV3iqhnKpnsk+Bj1jW8Zr/9rVEO3tWGCEIP5q+SOyzepW8v0t/xwvNHreVhFtlgrXiuQLQfaOy9bo7Rz43CyLmLmEvumyAgiwrjnsNgYOK8dU+rziKyWqikUFxSUC9x/U5W9hFHTF7v5ZifqO2UO2ZQ7zCNSKpk1aWhcODPxBwit3KItpyBhjj+L01kXDD3lzcMnRRvkp5Pp0u8MjAMaSS4TA/YL9ce+m/nWM+laxhLlRO0FSiOYk1r0OELxPlyDKSAbJul/VfZT8GynPIduds+l6XT6RlcEtvkg2I10Qsf8h4EdmbD2abla2lnQm1KvIpBbvfWGCGWIq3/EzSioiEeFoeo4KD8XNTtKVeUQ9N6B17bPOCx6/sjDqqvGd/NAuLQO+qP9Tar0AR/hjKcrIGrJDuK96tTCfbUCcCMaLDW3hLPtwvDSgS1rjX2lA5JD3ZBqFtyNMmhWnLhQsaullA==
  template:
    metadata:
      name: ssl-truststore-password
      namespace: event-streams
