---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ssl-truststore-password
  namespace: event-processing
spec:
  encryptedData:
    password: AgA45j40oMcGwg4QhqLUSgDfWdUbfMB4ezkR0CW6TySlaFGNz8bw9iyRJG+6RHbS4ojr8pCssyaKAP9CUU5ViJRvHOhanmkzcsyFqJVh6sb3uRRdM8Hmvb7sdYrI9txCTmPdgHJltGUgydKLyuEnldlTsfV1Tz+NbuQqp4XZkwZYUpP1Yu9uLcz98xebxxbAog3oVL6X2eqgw/A95ztGZzUcLGDYziT8EUcB3p7BJd6x0KGzh92Vw+uBKwW2KC9wYKXkEIym13TgvbmlhZsD7I7Ddlyvf47mbFpFsa1u8JDIQGdlPlH4fOYMkC5MypWPLRCJNiF52fGA3YgZoH8OSzKj39iQstdQriWvj8D5Osrgm0hZ8t4wyXPshU/5zmZACJIjv++O1nvebgwm1LHTGJ4wJaIBcRgIJfvJXhnOM3dX722wtjTbJ4So1VdRzOGUpDfyASchyhbhGEL6YijQu+vFcY65Jj7+GW1km1MKDr+a4cTqwi9iPFLtq2jCVNV3zHvsS9DnsQ/cPOcKdObbxWAoC5iVzGXoO7bftD33I8Rgawrlyl0ZdyQPKdfNuDuGuLcqE/AEmREvtVgRF15aeKuzAph2bp2mrEj0Td60fYlKkyXjBSCO+kvV5TwoQj1Ax6XAHeSeI8LVjdQWGuUWIGRiubTwS1iPX+Q+H/opGMKUOYrARmyKddJv+BcK/2Jb0QQ2J7XCDMCQZgevOtcYVZ0JP0+RjeYst8CazgflK8IcNw==
  template:
    metadata:
      name: ssl-truststore-password
      namespace: event-processing
