---
apiVersion: v1
kind: Namespace
metadata:
  name: event-endpoint-mgmt
  labels:
    app.kubernetes.io/name: event-endpoint-mgmt
    app.kubernetes.io/part-of: event-automation
    app.kubernetes.io/component: api-management
